name: Feature Request
description: Suggest a new feature or enhancement for merPCR
title: "[FEATURE] "
labels: [enhancement, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been suggested before
          required: true
        - label: I have checked if this feature exists in the original me-PCR or e-PCR tools
          required: true
        - label: I have considered if this could be achieved with existing functionality
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like merPCR to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Core Algorithm - Search algorithm improvements
        - Performance - Speed or memory optimizations
        - Input/Output - File format support or parsing
        - CLI - Command-line interface enhancements
        - API - Python API improvements
        - Testing - Testing infrastructure
        - Documentation - Documentation improvements
        - Other
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        I am working on... and I need this feature because...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, please share
      placeholder: This could be implemented by...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute to the implementation of this feature
        - label: I have the technical expertise to implement this feature
        - label: I can provide test data or help with testing this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples that would be helpful
      placeholder: Links to papers, similar tools, examples, etc.